package syrenyx.distantmoons.references.tag;

import net.minecraft.core.registries.Registries;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;
import syrenyx.distantmoons.UnderDistantMoons;

public abstract class DistantMoonsBlockTags {

  public static final TagKey<Block> BARS = keyOf("bars");
  public static final TagKey<Block> BARS_ALWAYS_CONNECTS_TO = keyOf("connection_target/bars/always");
  public static final TagKey<Block> BARS_NEVER_CONNECTS_TO = keyOf("connection_target/bars/never");
  public static final TagKey<Block> BEAM_ALWAYS_CONNECTS_TO = keyOf("connection_target/beam/always");
  public static final TagKey<Block> BEAM_ALWAYS_CONNECTS_TO_HORIZONTALLY = keyOf("connection_target/beam/horizontal/always");
  public static final TagKey<Block> BEAM_NEVER_CONNECTS_TO = keyOf("connection_target/beam/never");
  public static final TagKey<Block> BLOCK_TINT_PROVIDER_MOSS = keyOf("block_tint_provider/moss");
  public static final TagKey<Block> BLOCK_TINT_PROVIDER_PALE_MOSS = keyOf("block_tint_provider/pale_moss");
  public static final TagKey<Block> BRICK_FENCE = keyOf("brick_fence");
  public static final TagKey<Block> BRICK_FENCE_ALWAYS_CONNECTS_TO = keyOf("connection_target/brick_fence/always");
  public static final TagKey<Block> BRICK_FENCE_NEVER_CONNECTS_TO = keyOf("connection_target/brick_fence/never");
  public static final TagKey<Block> CHAIN = keyOf("chain");
  public static final TagKey<Block> CLIMBABLE = keyOf("misc/climbable");
  public static final TagKey<Block> DAMPENS_VIBRATIONS = keyOf("misc/dampens_vibrations");
  public static final TagKey<Block> DYED_CONCRETE_SLAB = keyOf("dyed/concrete_slab");
  public static final TagKey<Block> DYED_CONCRETE_STAIRS = keyOf("dyed/concrete_stairs");
  public static final TagKey<Block> DYED_CONCRETE_WALL_SLAB = keyOf("dyed/concrete_wall_slab");
  public static final TagKey<Block> DYED_PILLOW = keyOf("dyed/pillow");
  public static final TagKey<Block> DYED_STAINED_GLASS = keyOf("dyed/stained_glass");
  public static final TagKey<Block> DYED_STAINED_GLASS_PANE = keyOf("dyed/stained_glass_pane");
  public static final TagKey<Block> DYED_TERRACOTTA_SLAB = keyOf("dyed/terracotta_slab");
  public static final TagKey<Block> DYED_TERRACOTTA_STAIRS = keyOf("dyed/terracotta_stairs");
  public static final TagKey<Block> DYED_TERRACOTTA_WALL_SLAB = keyOf("dyed/terracotta_wall_slab");
  public static final TagKey<Block> FIXED_LADDER = keyOf("fixed_ladder");
  public static final TagKey<Block> FIXED_LADDER_ALWAYS_CONNECTS_TO = keyOf("connection_target/fixed_ladder/always");
  public static final TagKey<Block> FIXED_LADDER_ATTACHES_TO = keyOf("connection_target/fixed_ladder/attached");
  public static final TagKey<Block> FIXED_LADDER_CAPPED_TO = keyOf("connection_target/fixed_ladder/capped");
  public static final TagKey<Block> FIXED_LADDER_NEVER_CONNECTS_TO = keyOf("connection_target/fixed_ladder/never");
  public static final TagKey<Block> GLASS = keyOf("glass");
  public static final TagKey<Block> GLASS_PANE = keyOf("glass_pane");
  public static final TagKey<Block> GLASS_PANE_ALWAYS_CONNECTS_TO = keyOf("connection_target/glass_pane/always");
  public static final TagKey<Block> GLASS_PANE_NEVER_CONNECTS_TO = keyOf("connection_target/glass_pane/never");
  public static final TagKey<Block> IMMUNE_TO_DRAGON = keyOf("immunity/ender_dragon");
  public static final TagKey<Block> IMMUNE_TO_WITHER = keyOf("immunity/wither");
  public static final TagKey<Block> INFINIBURN_IN_THE_ABYSS = keyOf("infiniburn/the_abyss");
  public static final TagKey<Block> INFINIBURN_IN_THE_END = keyOf("infiniburn/the_end");
  public static final TagKey<Block> INFINIBURN_IN_THE_NETHER = keyOf("infiniburn/the_nether");
  public static final TagKey<Block> INFINIBURN_IN_OVERWORLD = keyOf("infiniburn/overworld");
  public static final TagKey<Block> INFINIBURN_UNIVERSAL = keyOf("infiniburn/universal");
  public static final TagKey<Block> LEAVES_WITHOUT_LEAF_PARTICLES = keyOf("misc/leaves_without_leaf_particles");
  public static final TagKey<Block> METAL_BAR_DOOR = keyOf("metal_bar_door");
  public static final TagKey<Block> METAL_BAR_DOOR_NEVER_CONNECTS_TO = keyOf("connection_target/metal_bar_door/never");
  public static final TagKey<Block> MINING_TIER_DIAMOND = keyOf("mining_tool_group/tier/diamond");
  public static final TagKey<Block> MINING_TIER_IRON = keyOf("mining_tool_group/tier/iron");
  public static final TagKey<Block> MINING_TIER_STONE = keyOf("mining_tool_group/tier/stone");
  public static final TagKey<Block> MINING_TYPE_AXE = keyOf("mining_tool_group/type/axe");
  public static final TagKey<Block> MINING_TYPE_HOE = keyOf("mining_tool_group/type/hoe");
  public static final TagKey<Block> MINING_TYPE_PICKAXE = keyOf("mining_tool_group/type/pickaxe");
  public static final TagKey<Block> MINING_TYPE_SHOVEL = keyOf("mining_tool_group/type/shovel");
  public static final TagKey<Block> NEVER_CONNECT_TO = keyOf("connection_target/never");
  public static final TagKey<Block> OCCLUDES_VIBRATIONS = keyOf("misc/occludes_vibrations");
  public static final TagKey<Block> OVERWORLD_SUBSTRATE = keyOf("misc/overworld_substrate");
  public static final TagKey<Block> OXIDIZABLE_CUT_COPPER_WALL_SLAB = keyOf("oxidizable/cut_copper_wall_slab");
  public static final TagKey<Block> OXIDIZABLE_IRON_BLOCK = keyOf("oxidizable/iron_block");
  public static final TagKey<Block> POLE_ALWAYS_CONNECTS_TO = keyOf("connection_target/pole/always");
  public static final TagKey<Block> POLE_ALWAYS_CONNECTS_TO_HORIZONTALLY = keyOf("connection_target/pole/horizontal/always");
  public static final TagKey<Block> POLE_NEVER_CONNECTS_TO = keyOf("connection_target/pole/never");
  public static final TagKey<Block> SHELF = keyOf("shelf");
  public static final TagKey<Block> SNIFFER_EGG_HATCH_BOOST = keyOf("misc/sniffer_egg_hatch_boost");
  public static final TagKey<Block> SPIKED_FENCE = keyOf("spiked_fence");
  public static final TagKey<Block> SPIKED_FENCE_ALWAYS_CONNECTS_TO = keyOf("connection_target/spiked_fence/always");
  public static final TagKey<Block> SPIKED_FENCE_NEVER_CONNECTS_TO = keyOf("connection_target/spiked_fence/never");
  public static final TagKey<Block> SPIKED_FENCE_NOT_BLOCKED_BY = keyOf("connection_target/spiked_fence/not_blocked_by");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_AZALEA = keyOf("support_block/azalea");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_AZALEA_GROWTH = keyOf("support_block/azalea_growth");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_BAMBOO = keyOf("support_block/bamboo");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_BIG_DRIPLEAF = keyOf("support_block/big_dripleaf");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_CRIMSON_FUNGUS = keyOf("support_block/crimson_fungus");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_CRIMSON_ROOTS = keyOf("support_block/crimson_roots");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_DRY_VEGETATION = keyOf("support_block/dry_vegetation");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_HUGE_BROWN_MUSHROOM_GROWTH = keyOf("support_block/huge_brown_mushroom_growth");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_HUGE_RED_MUSHROOM_GROWTH = keyOf("support_block/huge_red_mushroom_growth");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_MANGROVE_PROPAGULE = keyOf("support_block/mangrove_propagule");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_MELON_GROWTH = keyOf("support_block/melon_growth");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_NETHER_SPROUTS = keyOf("support_block/nether_sprouts");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_PUMPKIN_GROWTH = keyOf("support_block/pumpkin_growth");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_SITTING_SPOT = keyOf("support_block/sitting_spot");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_SMALL_DRIPLEAF = keyOf("support_block/small_dripleaf");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_SUGAR_CANE = keyOf("support_block/sugar_cane");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_VEGETATION = keyOf("support_block/vegetation");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_WARPED_FUNGUS = keyOf("support_block/warped_fungus");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_WARPED_ROOTS = keyOf("support_block/warped_roots");
  public static final TagKey<Block> SUPPORT_BLOCK_FOR_WITHER_ROSE = keyOf("support_block/wither_rose");
  public static final TagKey<Block> THIN_BALUSTRADE = keyOf("thin_balustrade");
  public static final TagKey<Block> THIN_BALUSTRADE_ALWAYS_CONNECTS_TO_HORIZONTALLY = keyOf("connection_target/thin_balustrade/horizontal/always");
  public static final TagKey<Block> THIN_BALUSTRADE_ALWAYS_CONNECTS_TO_VERTICALLY = keyOf("connection_target/thin_balustrade/vertical/always");
  public static final TagKey<Block> THIN_BALUSTRADE_NEVER_CONNECTS_TO_HORIZONTALLY = keyOf("connection_target/thin_balustrade/horizontal/never");
  public static final TagKey<Block> THIN_BALUSTRADE_NEVER_CONNECTS_TO_VERTICALLY = keyOf("connection_target/thin_balustrade/vertical/never");
  public static final TagKey<Block> THIN_BRANCH = keyOf("thin_branch");
  public static final TagKey<Block> THIN_BRANCH_ALWAYS_CONNECTS_TO = keyOf("connection_target/thin_branch/connects/always");
  public static final TagKey<Block> THIN_BRANCH_NEVER_CONNECTS_TO = keyOf("connection_target/thin_branch/connects/never");
  public static final TagKey<Block> THIN_BRANCH_EXTENDS_TO_HORIZONTALLY = keyOf("connection_target/thin_branch/extends/horizontal");
  public static final TagKey<Block> THIN_BRANCH_EXTENDS_TO_VERTICALLY = keyOf("connection_target/thin_branch/extends/vertical");
  public static final TagKey<Block> UNDERWORLD_COMPASS_TARGET = keyOf("misc/underworld_compass_target");
  public static final TagKey<Block> WALL = keyOf("wall");
  public static final TagKey<Block> WALL_ALWAYS_CONNECTS_TO = keyOf("connection_target/wall/always");
  public static final TagKey<Block> WALL_NEVER_CONNECTS_TO = keyOf("connection_target/wall/never");
  public static final TagKey<Block> WIDE_BALUSTRADE = keyOf("wide_balustrade");
  public static final TagKey<Block> WIDE_BALUSTRADE_ALWAYS_CONNECTS_TO_HORIZONTALLY = keyOf("connection_target/wide_balustrade/horizontal/always");
  public static final TagKey<Block> WIDE_BALUSTRADE_ALWAYS_CONNECTS_TO_VERTICALLY = keyOf("connection_target/wide_balustrade/vertical/always");
  public static final TagKey<Block> WIDE_BALUSTRADE_NEVER_CONNECTS_TO_HORIZONTALLY = keyOf("connection_target/wide_balustrade/horizontal/never");
  public static final TagKey<Block> WIDE_BALUSTRADE_NEVER_CONNECTS_TO_VERTICALLY = keyOf("connection_target/wide_balustrade/vertical/never");
  public static final TagKey<Block> WOODEN_BEAM = keyOf("wooden_beam");
  public static final TagKey<Block> WOODEN_FENCE = keyOf("wooden_fence");
  public static final TagKey<Block> WOODEN_FENCE_ALWAYS_CONNECTS_TO = keyOf("connection_target/wooden_fence/always");
  public static final TagKey<Block> WOODEN_FENCE_NEVER_CONNECTS_TO = keyOf("connection_target/wooden_fence/never");
  public static final TagKey<Block> WOODEN_POLE = keyOf("wooden_pole");
  public static final TagKey<Block> WORLDGEN_ANCHOR_CHAMBER_IGNORES = keyOf("worldgen/anchor_chamber_ignores");
  public static final TagKey<Block> WORLDGEN_IRREPLACEABLE = keyOf("worldgen/irreplaceable");

  private static TagKey<Block> keyOf(String id) {
    return UnderDistantMoons.tagKeyOf(id, Registries.BLOCK);
  }
}
